In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('./thoracic-data.csv')
# data = pd.DataFrame(data=rand.drop('id', index=1), index=rand['id'])
data

,id,DGN,PRE4,PRE5,PRE6,PRE7,PRE8,PRE9,PRE10,PRE11,PRE14,PRE17,PRE19,PRE25,PRE30,PRE32,AGE,Risk1Yr
0,1,DGN2,2.88,2.16,PRZ1,F,F,F,T,T,OC14,F,F,F,T,F,60,F
1,2,DGN3,3.40,1.88,PRZ0,F,F,F,F,F,OC12,F,F,F,T,F,51,F
2,3,DGN3,2.76,2.08,PRZ1,F,F,F,T,F,OC11,F,F,F,T,F,59,F
3,4,DGN3,3.68,3.04,PRZ0,F,F,F,F,F,OC11,F,F,F,F,F,54,F
4,5,DGN3,2.44,0.96,PRZ2,F,T,F,T,T,OC11,F,F,F,T,F,73,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
465,466,DGN2,3.88,2.12,PRZ1,F,F,F,T,F,OC13,F,F,F,T,F,63,F
466,467,DGN3,3.76,3.12,PRZ0,F,F,F,F,F,OC11,F,F,F,T,F,61,F
467,468,DGN3,3.04,2.08,PRZ1,F,F,F,T,F,OC13,F,F,F,F,F,52,F
468,469,DGN3,1.96,1.68,PRZ1,F,F,F,T,T,OC12,F,F,F,T,F,79,F
469,470,DGN3,4.72,3.56,PRZ0,F,F,F,F,F,OC12,F,F,F,T,F,51,F

In [3]:
data.index = data['id']
data.drop('id', axis = 1, inplace=True)

In [4]:
data

,DGN,PRE4,PRE5,PRE6,PRE7,PRE8,PRE9,PRE10,PRE11,PRE14,PRE17,PRE19,PRE25,PRE30,PRE32,AGE,Risk1Yr
id,,,,,,,,,,,,,,,,,
1,DGN2,2.88,2.16,PRZ1,F,F,F,T,T,OC14,F,F,F,T,F,60,F
2,DGN3,3.40,1.88,PRZ0,F,F,F,F,F,OC12,F,F,F,T,F,51,F
3,DGN3,2.76,2.08,PRZ1,F,F,F,T,F,OC11,F,F,F,T,F,59,F
4,DGN3,3.68,3.04,PRZ0,F,F,F,F,F,OC11,F,F,F,F,F,54,F
5,DGN3,2.44,0.96,PRZ2,F,T,F,T,T,OC11,F,F,F,T,F,73,T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,DGN2,3.88,2.12,PRZ1,F,F,F,T,F,OC13,F,F,F,T,F,63,F
467,DGN3,3.76,3.12,PRZ0,F,F,F,F,F,OC11,F,F,F,T,F,61,F
468,DGN3,3.04,2.08,PRZ1,F,F,F,T,F,OC13,F,F,F,F,F,52,F
469,DGN3,1.96,1.68,PRZ1,F,F,F,T,T,OC12,F,F,F,T,F,79,F
470,DGN3,4.72,3.56,PRZ0,F,F,F,F,F,OC12,F,F,F,T,F,51,F

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
data['DGN'] = le.fit_transform(data['DGN'])

# data['PRE4'] = le.fit_transform(data['PRE4'])

# data['PRE5'] = le.fit_transform(data['PRE5'])

data['PRE6'] = le.fit_transform(data['PRE6'])

data['PRE7'] = le.fit_transform(data['PRE7'])

data['PRE8'] = le.fit_transform(data['PRE8'])

data['PRE9'] = le.fit_transform(data['PRE9'])

data['PRE10'] = le.fit_transform(data['PRE10'])

data['PRE11'] = le.fit_transform(data['PRE11'])

data['PRE14'] = le.fit_transform(data['PRE14'])

data['PRE17'] = le.fit_transform(data['PRE17'])

data['PRE19'] = le.fit_transform(data['PRE19'])

data['PRE25'] = le.fit_transform(data['PRE25'])

data['PRE30'] = le.fit_transform(data['PRE30'])

data['PRE32'] = le.fit_transform(data['PRE32'])

data['Risk1Yr'] = le.fit_transform(data['Risk1Yr'])

In [7]:
data['Risk1Yr'].value_counts()

0    400
1     70
Name: Risk1Yr, dtype: int64

In [8]:
y = data['Risk1Yr']
x = data.drop(['Risk1Yr'], axis = 1)
x

,DGN,PRE4,PRE5,PRE6,PRE7,PRE8,PRE9,PRE10,PRE11,PRE14,PRE17,PRE19,PRE25,PRE30,PRE32,AGE
id,,,,,,,,,,,,,,,,
1,1,2.88,2.16,1,0,0,0,1,1,3,0,0,0,1,0,60
2,2,3.40,1.88,0,0,0,0,0,0,1,0,0,0,1,0,51
3,2,2.76,2.08,1,0,0,0,1,0,0,0,0,0,1,0,59
4,2,3.68,3.04,0,0,0,0,0,0,0,0,0,0,0,0,54
5,2,2.44,0.96,2,0,1,0,1,1,0,0,0,0,1,0,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466,1,3.88,2.12,1,0,0,0,1,0,2,0,0,0,1,0,63
467,2,3.76,3.12,0,0,0,0,0,0,0,0,0,0,1,0,61
468,2,3.04,2.08,1,0,0,0,1,0,2,0,0,0,0,0,52
469,2,1.96,1.68,1,0,0,0,1,1,1,0,0,0,1,0,79
470,2,4.72,3.56,0,0,0,0,0,0,1,0,0,0,1,0,51

In [9]:
y

id
1      0
2      0
3      0
4      0
5      1
      ..
466    0
467    0
468    0
469    0
470    0
Name: Risk1Yr, Length: 470, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3)

In [12]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(329, 16)
(141, 16)
(329,)
(141,)

In [13]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'poly', random_state = 1 )

In [14]:
classifier.fit(x_train, y_train)
y_pred = classifier.predict(x_test)

In [15]:
y_pred = classifier.predict(x_test)
from sklearn import metrics

print(metrics.accuracy_score(y_test, y_pred))
print(metrics.confusion_matrix(y_test, y_pred))

conf_mat = metrics.confusion_matrix(y_test, y_pred)
TP = conf_mat[0,0]
FP = conf_mat[1,0]
TN = conf_mat[1,1]
FN = conf_mat[0,1]
print(conf_mat)

sensitivity = TP/(TP+FN)
specificity = TN/(TN+FP)
precision = TP/(TP+FP)
pred_val = TN/(TN + FN)
accuracy = (TP + FN)/ (TP + TN + FP + FN)

print("sensitivity: ", sensitivity)
print("Precision: ", precision)
print("Specificity: ", specificity)
print("Predicted Value: ", pred_val)
print("Accuracy: ", accuracy)
print("Precision Score: ", metrics.precision_score(y_test, y_pred))
print("Recall Score: ", metrics.recall_score(y_test, y_pred))
print("F1 Score: ", metrics.f1_score(y_test, y_pred))

0.8439716312056738
[[119   0]
 [ 22   0]]
[[119   0]
 [ 22   0]]
sensitivity:  1.0
Precision:  0.8439716312056738
Specificity:  0.0
Predicted Value:  nan
Accuracy:  0.8439716312056738
Precision Score:  0.0
Recall Score:  0.0
F1 Score:  0.0

/home/bharath/.local/lib/python3.6/site-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in long_scalars
/home/bharath/.local/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [16]:
from os import system, name 
def clear():
    if name == 'nt': 
        _ = system('cls') 
    else: 
        _ = system('clear')

In [17]:
def userinp():
    put = []
    put.append(input("Please enter the disease your diagnosed wth from the following options: \nDGN3, DGN2, DGN4, DGN6, DGN5, DGN8, DGN1. \n").upper())
    clear()
    put.append(float(input("Please enter your forced vital capacity:\n")))
    clear()
    put.append(float(input("Please enter the value of you FEV1:\n")))
    clear()
    put.append(input("Please enter the disease your Performance Status from the following options: \nPRZ2, PRZ1, PRZ0. \n").upper())
    clear()
    put.append(input("Please enter 'T' if you've experienced any pain before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've experienced any haemoptysis before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've experienced any Dyspnoea before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've had any cough before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've had any weakness before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter the size of the tumour from the following options: \nOC11, OC12, OC13, OC14(With OC11 being the samllest and OC14 the largest )\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've had any diabetes mellitus(DM) before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've had any MI (Myocardial Infarction) before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've had any peripheral arterial diseases  before surgery andd 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've a habit of smoking and 'F' if not\n").upper())
    clear()
    put.append(input("Please enter 'T' if you've asthma and 'F' if not\n").upper())
    clear()
    put.append(input("Please enter your age:\n"))
    clear()
    temp = pd.DataFrame(put,index = x.columns).transpose()
    dat = pd.read_csv('./thoracic-data.csv').drop(['id', 'Risk1Yr'], axis = 1)
    for i in list(dat.columns):
        if i != 'AGE' and i != 'PRE4' and i != 'PRE5':
            le.fit(dat[i])
            temp[i] = le.transform(temp[i])
    if classifier.predict(temp) == 0:
        print("You've been tested negative of the risk in dying within one year")
    else:
        print("You've been tested negative of the risk in dying within one year")

In [18]:
userinp()

Please enter the disease your diagnosed wth from the following options:
DGN3, DGN2, DGN4, DGN6, DGN5, DGN8, DGN1.
dgn1
Please enter your forced vital capacity:
12.2
Please enter the value of you FEV1:
100
Please enter the disease your Performance Status from the following options:
PRZ2, PRZ1, PRZ0.
PRZ2
Please enter 'T' if you've experienced any pain before surgery andd 'F' if not
t
Please enter 'T' if you've experienced any haemoptysis before surgery andd 'F' if not
f
Please enter 'T' if you've experienced any Dyspnoea before surgery andd 'F' if not
t
Please enter 'T' if you've had any cough before surgery andd 'F' if not
t
Please enter 'T' if you've had any weakness before surgery andd 'F' if not
t
Please enter the size of the tumour from the following options:
OC11, OC12, OC13, OC14(With OC11 being the samllest and OC14 the largest )
oc14
Please enter 'T' if you've had any diabetes mellitus(DM) before surgery andd 'F' if not
t
Please enter 'T' if you've had any MI (Myocardial Infarction) before surgery andd 'F' if not
t
Please enter 'T' if you've had any peripheral arterial diseases  before surgery andd 'F' if not
t
Please enter 'T' if you've a habit of smoking and 'F' if not
t
Please enter 'T' if you've asthma and 'F' if not
t
Please enter your age:
80
You've been tested negative of the risk in dying within one year